spring.application.name=LoginAuthentication
# ===============================
# Oracle Datasource
# ===============================
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=system
spring.datasource.password=oracle

# ===============================
# MyBatis
# ===============================
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=com.loginAuth.dto
mybatis.configuration.map-underscore-to-camel-case=true

# ===============================
# Server
# ===============================
server.port=8080


# ===============================
# Email (SMTP - Gmail)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=loginauthentication.2025@gmail.com
spring.mail.password=hcgo qzbx crco btlu

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

#  ===============================
# OAuth2 - Google Login
# ===============================
#spring.security.oauth2.client.registration.google.client-id=1097134903610-72ijprg2rev5t4s4pph2v3aosuujkdls.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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

#spring.security.oauth2.client.registration.google.scope=profile,email
#spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}


